//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE_DETAILS
    {
        public long ATNDNC_ID { get; set; }
        public long EMPLOYEE_ID { get; set; }
        public System.DateTime ATT_DATE { get; set; }
        public Nullable<System.TimeSpan> CHECK_IN_TIME { get; set; }
        public Nullable<System.TimeSpan> CHECK_OUT_TIME { get; set; }
        public Nullable<int> SL_NO { get; set; }
        public string STATUS { get; set; }
    
        public virtual EMPLOYEE_INFO EMPLOYEE_INFO { get; set; }
    }
}
