//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUEPMENTS_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUEPMENTS_INFO()
        {
            this.ASSET_MANAGEMENT = new HashSet<ASSET_MANAGEMENT>();
        }
    
        public long EQUEPMENT_ID { get; set; }
        public string EQP_TITLE { get; set; }
        public long ASSET_ID { get; set; }
        public string MODEL_NO { get; set; }
        public string SERIAL_NO { get; set; }
        public long ACTION_BY { get; set; }
        public System.DateTime ACTION_DATE { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual ASSET_INFO ASSET_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSET_MANAGEMENT> ASSET_MANAGEMENT { get; set; }
    }
}
