//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_INFO()
        {
            this.STOCK_INFO = new HashSet<STOCK_INFO>();
        }
    
        public long INV_ID { get; set; }
        public long EQP_ID { get; set; }
        public long VENDOR_ID { get; set; }
        public int UNIT { get; set; }
        public string DATE { get; set; }
        public string STOCK_TYPE { get; set; }
        public System.DateTime ACTION_DATE { get; set; }
        public long ACTION_BY { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string NOTE { get; set; }
        public string TAG_NO { get; set; }
    
        public virtual EQUEPMENTS_INFO EQUEPMENTS_INFO { get; set; }
        public virtual VENDOR_INFO VENDOR_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_INFO> STOCK_INFO { get; set; }
    }
}
