//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LEAVE_TYPE()
        {
            this.LEAVE_APPLICATION = new HashSet<LEAVE_APPLICATION>();
        }
    
        public long LEAVE_ID { get; set; }
        public string LEAVE_TITLE { get; set; }
        public string REMARKS { get; set; }
        public long ACTIVE_BY { get; set; }
        public System.DateTime ACTIVE_DATE { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAVE_APPLICATION> LEAVE_APPLICATION { get; set; }
    }
}
