//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARY_INFO_SUM
    {
        public long SALARY_INFO_SUM_ID { get; set; }
        public string SALARY_PAID_MONTH { get; set; }
        public decimal TOTAL_PAID { get; set; }
    }
}
