//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_INFO
    {
        public long STOCK_ID { get; set; }
        public long EQP_ID { get; set; }
        public int UNIT { get; set; }
        public string STOCK_TYPE { get; set; }
        public string STOCK_FOR { get; set; }
        public long ACTION_BY { get; set; }
        public System.DateTime ACTION_DATE { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public long INV_ID { get; set; }
    
        public virtual EQUEPMENTS_INFO EQUEPMENTS_INFO { get; set; }
        public virtual INV_INFO INV_INFO { get; set; }
    }
}
