//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public long ID { get; set; }
        public Nullable<long> EMPLOYEE_ID { get; set; }
        public string USER_NAME { get; set; }
        public string CONTACT { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string USER_LEVEL { get; set; }
        public string IS_DELETED { get; set; }
        public Nullable<System.DateTime> ACTION_DATE { get; set; }
        public Nullable<long> ACTION_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
    
        public virtual EMPLOYEE_INFO EMPLOYEE_INFO { get; set; }
    }
}
